// flow-typed signature: 56e2395ac9108e0060f0401eb068b339
// flow-typed version: <<STUB>>/mdg-borealis_v^1.0.8/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mdg-borealis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mdg-borealis' {
  declare module.exports: any;
}
