// flow-typed signature: 3f64c99aff2b9d3e470e2294cd697369
// flow-typed version: <<STUB>>/prettier-check_v^1.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-check'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-check' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-check/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-check/cli.js' {
  declare module.exports: $Exports<'prettier-check/cli'>;
}
declare module 'prettier-check/index' {
  declare module.exports: $Exports<'prettier-check'>;
}
declare module 'prettier-check/index.js' {
  declare module.exports: $Exports<'prettier-check'>;
}
