// flow-typed signature: 9b5409c3e508cc99de87f7487137512c
// flow-typed version: <<STUB>>/wt-cli_v^6.1.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wt-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wt-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wt-cli/bin/_plugins/profile' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/_plugins/profileOptions' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/auth0_create' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/auth0_ls' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/auth0_scaffold' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/auth0_toggle' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/browser_logs' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/bundle' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/bundle/analyze' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/bundle/sync' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/create' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/cron' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/cron/get' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/cron/history' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/cron/ls' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/cron/rm' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/cron/schedule' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/debug' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/edit' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/init' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/inspect' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/logs' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/ls' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/modules' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/modules/add' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/modules/versions' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/mv' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/profile' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/profile/get' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/profile/init' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/profile/ls' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/profile/nuke' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/profile/rm' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/rm' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/serve' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/serveCommon' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/token' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/token/create' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/token/inspect' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/token/revoke' {
  declare module.exports: any;
}

declare module 'wt-cli/bin/update' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/config' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/createWebtask' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/errors' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/keyValList2Object' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/logs' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/modules' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/printCronJob' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/printProfile' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/printTokenDetails' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/printWebtask' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/userVerifier' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/validateCreateArgs' {
  declare module.exports: any;
}

declare module 'wt-cli/lib/webtaskCreator' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/attack-cpu' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/attack-forkbomb' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/attack-ram' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/bundled-webtask/data' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/bundled-webtask/index' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/counter' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/csharp' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/es6-template-literals' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/es6' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/express' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/github-tag-hook' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/google-places-api' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/hello-world' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/html-response' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/httppost' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/json-response' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/logging' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/mongodb' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/request' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/unverified-emails' {
  declare module.exports: any;
}

declare module 'wt-cli/sample-webtasks/url-query-parameter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wt-cli/bin/_plugins/profile.js' {
  declare module.exports: $Exports<'wt-cli/bin/_plugins/profile'>;
}
declare module 'wt-cli/bin/_plugins/profileOptions.js' {
  declare module.exports: $Exports<'wt-cli/bin/_plugins/profileOptions'>;
}
declare module 'wt-cli/bin/auth0_create.js' {
  declare module.exports: $Exports<'wt-cli/bin/auth0_create'>;
}
declare module 'wt-cli/bin/auth0_ls.js' {
  declare module.exports: $Exports<'wt-cli/bin/auth0_ls'>;
}
declare module 'wt-cli/bin/auth0_scaffold.js' {
  declare module.exports: $Exports<'wt-cli/bin/auth0_scaffold'>;
}
declare module 'wt-cli/bin/auth0_toggle.js' {
  declare module.exports: $Exports<'wt-cli/bin/auth0_toggle'>;
}
declare module 'wt-cli/bin/browser_logs.js' {
  declare module.exports: $Exports<'wt-cli/bin/browser_logs'>;
}
declare module 'wt-cli/bin/bundle.js' {
  declare module.exports: $Exports<'wt-cli/bin/bundle'>;
}
declare module 'wt-cli/bin/bundle/analyze.js' {
  declare module.exports: $Exports<'wt-cli/bin/bundle/analyze'>;
}
declare module 'wt-cli/bin/bundle/sync.js' {
  declare module.exports: $Exports<'wt-cli/bin/bundle/sync'>;
}
declare module 'wt-cli/bin/create.js' {
  declare module.exports: $Exports<'wt-cli/bin/create'>;
}
declare module 'wt-cli/bin/cron.js' {
  declare module.exports: $Exports<'wt-cli/bin/cron'>;
}
declare module 'wt-cli/bin/cron/get.js' {
  declare module.exports: $Exports<'wt-cli/bin/cron/get'>;
}
declare module 'wt-cli/bin/cron/history.js' {
  declare module.exports: $Exports<'wt-cli/bin/cron/history'>;
}
declare module 'wt-cli/bin/cron/ls.js' {
  declare module.exports: $Exports<'wt-cli/bin/cron/ls'>;
}
declare module 'wt-cli/bin/cron/rm.js' {
  declare module.exports: $Exports<'wt-cli/bin/cron/rm'>;
}
declare module 'wt-cli/bin/cron/schedule.js' {
  declare module.exports: $Exports<'wt-cli/bin/cron/schedule'>;
}
declare module 'wt-cli/bin/debug.js' {
  declare module.exports: $Exports<'wt-cli/bin/debug'>;
}
declare module 'wt-cli/bin/edit.js' {
  declare module.exports: $Exports<'wt-cli/bin/edit'>;
}
declare module 'wt-cli/bin/init.js' {
  declare module.exports: $Exports<'wt-cli/bin/init'>;
}
declare module 'wt-cli/bin/inspect.js' {
  declare module.exports: $Exports<'wt-cli/bin/inspect'>;
}
declare module 'wt-cli/bin/logs.js' {
  declare module.exports: $Exports<'wt-cli/bin/logs'>;
}
declare module 'wt-cli/bin/ls.js' {
  declare module.exports: $Exports<'wt-cli/bin/ls'>;
}
declare module 'wt-cli/bin/modules.js' {
  declare module.exports: $Exports<'wt-cli/bin/modules'>;
}
declare module 'wt-cli/bin/modules/add.js' {
  declare module.exports: $Exports<'wt-cli/bin/modules/add'>;
}
declare module 'wt-cli/bin/modules/versions.js' {
  declare module.exports: $Exports<'wt-cli/bin/modules/versions'>;
}
declare module 'wt-cli/bin/mv.js' {
  declare module.exports: $Exports<'wt-cli/bin/mv'>;
}
declare module 'wt-cli/bin/profile.js' {
  declare module.exports: $Exports<'wt-cli/bin/profile'>;
}
declare module 'wt-cli/bin/profile/get.js' {
  declare module.exports: $Exports<'wt-cli/bin/profile/get'>;
}
declare module 'wt-cli/bin/profile/init.js' {
  declare module.exports: $Exports<'wt-cli/bin/profile/init'>;
}
declare module 'wt-cli/bin/profile/ls.js' {
  declare module.exports: $Exports<'wt-cli/bin/profile/ls'>;
}
declare module 'wt-cli/bin/profile/nuke.js' {
  declare module.exports: $Exports<'wt-cli/bin/profile/nuke'>;
}
declare module 'wt-cli/bin/profile/rm.js' {
  declare module.exports: $Exports<'wt-cli/bin/profile/rm'>;
}
declare module 'wt-cli/bin/rm.js' {
  declare module.exports: $Exports<'wt-cli/bin/rm'>;
}
declare module 'wt-cli/bin/serve.js' {
  declare module.exports: $Exports<'wt-cli/bin/serve'>;
}
declare module 'wt-cli/bin/serveCommon.js' {
  declare module.exports: $Exports<'wt-cli/bin/serveCommon'>;
}
declare module 'wt-cli/bin/token.js' {
  declare module.exports: $Exports<'wt-cli/bin/token'>;
}
declare module 'wt-cli/bin/token/create.js' {
  declare module.exports: $Exports<'wt-cli/bin/token/create'>;
}
declare module 'wt-cli/bin/token/inspect.js' {
  declare module.exports: $Exports<'wt-cli/bin/token/inspect'>;
}
declare module 'wt-cli/bin/token/revoke.js' {
  declare module.exports: $Exports<'wt-cli/bin/token/revoke'>;
}
declare module 'wt-cli/bin/update.js' {
  declare module.exports: $Exports<'wt-cli/bin/update'>;
}
declare module 'wt-cli/index' {
  declare module.exports: $Exports<'wt-cli'>;
}
declare module 'wt-cli/index.js' {
  declare module.exports: $Exports<'wt-cli'>;
}
declare module 'wt-cli/lib/config.js' {
  declare module.exports: $Exports<'wt-cli/lib/config'>;
}
declare module 'wt-cli/lib/createWebtask.js' {
  declare module.exports: $Exports<'wt-cli/lib/createWebtask'>;
}
declare module 'wt-cli/lib/errors.js' {
  declare module.exports: $Exports<'wt-cli/lib/errors'>;
}
declare module 'wt-cli/lib/keyValList2Object.js' {
  declare module.exports: $Exports<'wt-cli/lib/keyValList2Object'>;
}
declare module 'wt-cli/lib/logs.js' {
  declare module.exports: $Exports<'wt-cli/lib/logs'>;
}
declare module 'wt-cli/lib/modules.js' {
  declare module.exports: $Exports<'wt-cli/lib/modules'>;
}
declare module 'wt-cli/lib/printCronJob.js' {
  declare module.exports: $Exports<'wt-cli/lib/printCronJob'>;
}
declare module 'wt-cli/lib/printProfile.js' {
  declare module.exports: $Exports<'wt-cli/lib/printProfile'>;
}
declare module 'wt-cli/lib/printTokenDetails.js' {
  declare module.exports: $Exports<'wt-cli/lib/printTokenDetails'>;
}
declare module 'wt-cli/lib/printWebtask.js' {
  declare module.exports: $Exports<'wt-cli/lib/printWebtask'>;
}
declare module 'wt-cli/lib/userVerifier.js' {
  declare module.exports: $Exports<'wt-cli/lib/userVerifier'>;
}
declare module 'wt-cli/lib/validateCreateArgs.js' {
  declare module.exports: $Exports<'wt-cli/lib/validateCreateArgs'>;
}
declare module 'wt-cli/lib/webtaskCreator.js' {
  declare module.exports: $Exports<'wt-cli/lib/webtaskCreator'>;
}
declare module 'wt-cli/sample-webtasks/attack-cpu.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/attack-cpu'>;
}
declare module 'wt-cli/sample-webtasks/attack-forkbomb.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/attack-forkbomb'>;
}
declare module 'wt-cli/sample-webtasks/attack-ram.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/attack-ram'>;
}
declare module 'wt-cli/sample-webtasks/bundled-webtask/data.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/bundled-webtask/data'>;
}
declare module 'wt-cli/sample-webtasks/bundled-webtask/index.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/bundled-webtask/index'>;
}
declare module 'wt-cli/sample-webtasks/counter.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/counter'>;
}
declare module 'wt-cli/sample-webtasks/csharp.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/csharp'>;
}
declare module 'wt-cli/sample-webtasks/es6-template-literals.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/es6-template-literals'>;
}
declare module 'wt-cli/sample-webtasks/es6.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/es6'>;
}
declare module 'wt-cli/sample-webtasks/express.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/express'>;
}
declare module 'wt-cli/sample-webtasks/github-tag-hook.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/github-tag-hook'>;
}
declare module 'wt-cli/sample-webtasks/google-places-api.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/google-places-api'>;
}
declare module 'wt-cli/sample-webtasks/hello-world.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/hello-world'>;
}
declare module 'wt-cli/sample-webtasks/html-response.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/html-response'>;
}
declare module 'wt-cli/sample-webtasks/httppost.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/httppost'>;
}
declare module 'wt-cli/sample-webtasks/json-response.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/json-response'>;
}
declare module 'wt-cli/sample-webtasks/logging.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/logging'>;
}
declare module 'wt-cli/sample-webtasks/mongodb.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/mongodb'>;
}
declare module 'wt-cli/sample-webtasks/request.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/request'>;
}
declare module 'wt-cli/sample-webtasks/unverified-emails.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/unverified-emails'>;
}
declare module 'wt-cli/sample-webtasks/url-query-parameter.js' {
  declare module.exports: $Exports<'wt-cli/sample-webtasks/url-query-parameter'>;
}
